[build]
  command = "npm install --legacy-peer-deps --force && npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"

# Required Environment Variables
# These must be set in the Netlify UI (Site settings > Environment variables)
#
# NEXT_PUBLIC_WORLD_APP_ID                 (Required) Your World App ID from the World Developer Portal
# NEXT_PUBLIC_LENDING_CONTRACT_ADDRESS     (Required) Your deployed lending contract address
# NEXT_PUBLIC_WORLD_CHAIN_RPC_URL         (Required) World Chain RPC URL (default: https://rpc.world.org)
#
# To set these variables:
# 1. Go to your Netlify site dashboard
# 2. Navigate to Site settings > Environment variables
# 3. Add each variable with its corresponding value
# 4. Trigger a new deployment

# Needed when using static export
[functions]
  included_files = ["!node_modules/sharp/**/*"]

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "frame-ancestors 'none'" 